/**
 * Generates src/components/icons/lucide-glyphs.ts from the Lucide icon set.
 *
 * Only the icons listed below are bundled, so the app never ships the full
 * ~1,800-icon library. To add an icon, find its file name on https://lucide.dev,
 * add it to ICONS and run `npm run icons`.
 *
 * Lucide is ISC licensed: https://github.com/lucide-icons/lucide/blob/main/LICENSE
 */
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);

/** App icon name -> Lucide file name. */
const ICONS = {
  home: 'house',
  stylist: 'sparkles',
  sparkle: 'sparkle',
  bag: 'shopping-bag',
  account: 'user-round',
  heart: 'heart',
  back: 'chevron-left',
  chevronRight: 'chevron-right',
  chevronDown: 'chevron-down',
  chevronUp: 'chevron-up',
  arrowRight: 'arrow-right',
  moreVertical: 'ellipsis-vertical',
  moreHorizontal: 'ellipsis',
  settings: 'settings',
  camera: 'camera',
  image: 'image',
  images: 'images',
  lock: 'lock',
  mail: 'mail',
  trash: 'trash',
  swap: 'refresh-cw',
  plus: 'plus',
  minus: 'minus',
  check: 'check',
  close: 'x',
  send: 'send',
  mapPin: 'map-pin',
  clock: 'clock',
  archive: 'archive',
  menu: 'menu',
  search: 'search',
  info: 'info',
  alert: 'circle-alert',
  wifiOff: 'wifi-off',
  cloudOff: 'cloud-off',
  sliders: 'sliders-horizontal',
  shieldCheck: 'shield-check',
  checkCircle: 'circle-check',
  logOut: 'log-out',
  externalLink: 'external-link',
  flag: 'flag',
  retry: 'rotate-ccw',
  calendar: 'calendar',
  message: 'message-circle',
  ruler: 'ruler',
  package: 'package',
  eye: 'eye',
  undo: 'undo-2',
};

const iconsDir = join(dirname(require.resolve('lucide/package.json')), 'dist/esm/icons');
const version = require('lucide/package.json').version;

const entries = [];
for (const [name, file] of Object.entries(ICONS)) {
  const mod = await import(pathToFileURL(join(iconsDir, `${file}.mjs`)).href);
  const nodes = mod.default.map(([tag, attrs]) => {
    const { key: _key, ...rest } = attrs;
    return [tag, rest];
  });
  entries.push(`  ${name}: ${JSON.stringify(nodes)},`);
}

const output = `// Generated by scripts/generate-icons.mjs from Lucide v${version} (ISC License).
// Do not edit by hand: add names to scripts/generate-icons.mjs and run \`npm run icons\`.
import type { GlyphNode } from './glyph-types';

export const lucideGlyphs = {
${entries.join('\n')}
} satisfies Record<string, GlyphNode[]>;
`;

const target = new URL('../src/components/icons/lucide-glyphs.ts', import.meta.url);
writeFileSync(target, output);
console.log(`Wrote ${entries.length} icons to src/components/icons/lucide-glyphs.ts`);
